### ISSUE TITLE
Race condition while trying to connect

### ISSUE THREAD

**Issue by eqdw** [hybridgroup/artoo-arduino#12]
I am following the quickstart instructions [here](http://artoo.io/documentation/platforms/arduino/) and [here](http://artoo.io/documentation/drivers/led/) and am unable to get the arduino connected. However, when doing this manually via the ruby console, or by dropping in to the relevant section of code with a debugger, it works.

Investigation revealed the following: https://github.com/hybridgroup/artoo-arduino/blob/master/lib/artoo/adaptors/firmata.rb#L15-L16. With my Arduino, `@firmata = ::Firmata::Board.new(connect_to)` causes the status LED on my Arduino to flicker for a few seconds, presumably rebooting, flushing memory, or doing something. If the following line of code `@firmata.connect` is called before the status LED stops flashing, no connection will be made and my Artoo program will hang indefinitely. However, if I pause execution of the software long enough for the Arduino to finish what it's doing (`sleep(3)` seems to be sufficient) then the connection will succeed and my program continues executing as expected.

Wondering if some light could be shed on this. Is there something wrong with my Arduino configuration, or is this a bug in the library? I tried to write a proper patch for this (perhaps passing a block in to `Firmata::Board.new` to execute the `@firmata.connect` when the Arduino stabilizes) but I'm not familiar enough with serial port stuff to do this. In the mean time, as I said above, I'm using `sleep(3)` as a workaround

**Comment by deadprogram** [comment]
Can you please provide some additional info:
- OS & version
- Ruby version
- Any backtrace thrown when you try to connect without the extra delay...

Thanks!

**Comment by eqdw** [comment]
OS: OSX 10.8.4
Ruby version: Tried with 2.0.0-p353, 2.1.0, and rubinius 2.1.1. All show the same behaviour

There is no backtrace thrown when I try to connect. It just hangs. The output proceeds as normal but it never gets past the "connecting to 'arduino'" line. Like so

```
, [2014-01-03T16:24:56.508351 #33838]  INFO -- : Registering connection 'arduino'...
I, [2014-01-03T16:24:56.508441 #33838]  INFO -- : Registering device 'board'...
I, [2014-01-03T16:24:56.508469 #33838]  INFO -- : Registering device 'servo'...
I, [2014-01-03T16:24:56.508494 #33838]  INFO -- : Registering api...
I, [2014-01-03T16:24:56.508516 #33838]  INFO -- : Preparing work...
I, [2014-01-03T16:24:56.509063 #33838]  INFO -- : Initializing connection arduino...
I, [2014-01-03T16:24:56.517012 #33838]  INFO -- : Initializing device board...
I, [2014-01-03T16:24:56.518369 #33838]  INFO -- : Initializing device servo...
I, [2014-01-03T16:24:56.526151 #33838]  INFO -- : Starting work...
I, [2014-01-03T16:24:56.526406 #33838]  INFO -- : Connecting to 'arduino' on port '/dev/tty.usbmodem1411'...
```

**Comment by deadprogram** [comment]
@edgarSilva can you please look into this?

**Comment by edgarsilva** [comment]
Definitely, @eqdw What type of arduino are you working on?

**Comment by eqdw** [comment]
It's an Arduino Uno running the latest version of Firmata (downloaded last Friday). It's my friend's Arduino and I'm not super familiar with them, so I don't know if there is a hardware revision number that's important

**Comment by edgarsilva** [comment]
Not really (the hardware revision), there are a couple of known issues with other arduinos like the mega and firmata, but the UNO should work fine. It must be software related either OS or serial port connection. I will take a look into the code and let you know. I will probably need your help to test since I do not have a mac.

I'll keep you posted.

**Comment by eqdw** [comment]
Awesome! Thanks a bunch for this. This took an embarrassingly long time for me to diagnose; I've been out of hardware too long.

We were working with this as part of a hackathon at work, and that hackathon has ended, so I'll be restricted to trying to help in the evenings. That said, I'm more than open to helping in my evenings.

**Comment by edgarsilva** [comment]
Great, we can agree on some time to debug later this week, or over the weekend if that is easier for you, just let me know, in the meantime I'll test here and pull the repo to create a version of the adapter that has several lines of debugging comments, to check where is the race condition happening.

**Comment by solojavier** [comment]
is it fine if we close this issue? or is there anything else we can do to move this forward?

cc. @edgarsilva  @eqdw

**Comment by ghost** [comment]
Hey all, just wondering if this one ever got resolved? I just bought a new Arduino Uno today and am running into the same issue as @eqdw. This is on:
- OS X 10.9.4
- Ruby 2.1.2
- artoo 1.8.0
- artoo-arduino 1.4.4

Thank you!

**Comment by solojavier** [comment]
Could you try using "/dev/cu.usbmodem1411" instead of "/dev/tty.usbmodem1411" ?

Also verify it's the correct port...

**Comment by solojavier** [comment]
@eqdw are you still having this issue?

**Comment by eqdw** [comment]
@solojavier I passed this off to a coworker, and the actual project is working now. So I'm assuming that no, we are no longer having this problem. Thanks!

**Comment by solojavier** [comment]
tty :shipit:
