### ISSUE TITLE
Artoo firmata upload command doesn't accept serial argument

### ISSUE THREAD

**Issue by zachrab** [hybridgroup/artoo-arduino#15]
When trying to upload firmata to the arduino I am unable to pass a serial as an argument. 

> > artoo firmata upload tty.usbmodem1411
> > ERROR: artoo upload was called with arguments ["tty.usbmodem1411"]
> > Usage: "artoo firmata upload".

**Comment by edgarsilva** [comment]
Hi,

Are you on a Mac? you need to provide the full path to the serial, exactly as it is shown when you run:

```
$ artoo connect scan -t serial
```

It should be something like:

```
artoo firmata upload /dev/tty.usbmodem1411
```

**Comment by zachrab** [comment]
Tried that also still receive: 

> > artoo firmata upload /dev/tty.usbmodem1411
> > ERROR: artoo upload was called with arguments ["/dev/tty.usbmodem1411"]
> > Usage: "artoo firmata upload".

**Comment by deadprogram** [comment]
We should allow user to enter full path /dev/ttyACM0 in which case we do no path munging

**Comment by deadprogram** [comment]
In other words commands should be able to take the full path to port. It should be `artoo firmata upload /dev/tty.usbmodem1411` and `artoo connect serial /dev/tty.usbmodem1411 4567` etc.

**Comment by edgarsilva** [comment]
Right now it is like that, it accepts the full path, but not partial path or just the name of the path.
Working on this, I will make it so it accepts both the entire path and just the file name of the device.

**Comment by deadprogram** [comment]
Also, @edgarSilva you should be using a param not an option flag.

**Comment by edgarsilva** [comment]
@zachrab We pushed some updates earlier this week, can you pls give it a try when you have a chance and let us know how it goes?

commands should work as you had it originally:

```
artoo firmata upload tty.usbmodem1411
```

**Comment by gomayonqui** [comment]
Same here 

```
artoo firmata upload tty.usbmodem1411
ERROR: artoo upload was called with arguments ["tty.usbmodem1411"]
Usage: "artoo firmata upload".
```

**Comment by edgarsilva** [comment]
@gomayonqui What version of the artoo and artoo-arduino gems are you using? We did some updates to the commands, they should be available in the latest version.

**Comment by gomayonqui** [comment]
artoo (1.6.1)
artoo-arduino (1.4.0)

ruby 1.9.3p448

I'm on Mac OS
Thanks for your quick answer!

**Comment by edgarsilva** [comment]
Let me take a look into this, the way you called it should be the correct way. I'll update here in a few.

**Comment by gomayonqui** [comment]
I'm trying it in a Arduino Leonardo, just in case.

**Comment by edgarsilva** [comment]
The arduino leonardo has the same pinout the UNO has, so it should work fine, the only arduino with known issues using firmata is the MEGA.

I found out the issue, we'll push a fix in a little bit. The latest gem build pushed to RubyGems was not pushed correctly, the code is actually correct in the github repo, but not in the gem.

You can always pull the repo and build the gem locally, should work fine, or just wait for like an hour and the gem should work fine then.

**Comment by gomayonqui** [comment]
Going to try it out!
Gracias! @edgarSilva

**Comment by edgarsilva** [comment]
This should be working now, @gomayonqui & @zachrab can you pls give it a try and let me know?

```
artoo firmata upload tty.usbmodem1411
```

The new version of the gem is 1.4.1.

**Comment by edgarsilva** [comment]
@gomayonqui @zachrab Let me know when tested so I can close this issue. Thanks!

**Comment by solojavier** [comment]
I'm closing this issue now.. @gomayonqui feel free to re-open if you find it is still happening.
