### ISSUE TITLE
Firmata and bluetooth

### ISSUE THREAD

**Issue by eltados** [hybridgroup/artoo-arduino#25]
Hi , first of all awesome project I have been having a lot of fun with it !
I have 2 questions / issues :
- Why did you fork the firmata gem to use inside of artoo-arduino ? 
- Have you ever tested to connect to the arduino using artoo / your version of the firmata gem / FirmataStandard 2.3 via bluetooth  ? 

I cannot connect via bluetooth,  when execution this line 
`
connection :firmata, :adaptor => :firmata, :port => '/dev/rfcomm0' # i'm using linux
`
I get an infinite loop in Firmata::Board#connect  ( in the block catch(:initialized) do ).

Do you have any idea what might cause this problem ? 
Do you ever connect to an arduino board via bluetooth using firmata  ?  Is it even possible ?

Cheers

**Comment by solojavier** [comment]
Hi @eltados,

Thanks for writing...

**Why did you fork the firmata gem to use inside of artoo-arduino ?**

Because we added the ability to use socket to serial connections, not just serial, so we could take advantage of Celluloid-IO's non-blocking IO, we also changed the way events are handled in our fork of firmata

**Have you ever tested to connect to the arduino using artoo / your version of the firmata gem / FirmataStandard 2.3 via bluetooth ?**
Not exactly, but it is exactly the same as we do to communicate with Sphero, you could try this steps: http://artoo.io/documentation/platforms/sphero/#HowToConnect but changing sphero references to arduino...

Let us know if you find further issues...

Also you can find us on IRC #artoo freenode.

**Comment by eltados** [comment]
Ok I now get why you forked firmata. Cheers for the explaination.
Concerning the connection via bluetooth, I followed your tutorial :
And run the command to connect in one terminal :

```
mathieu@mathieu-laptop ~/ruby $ artoo bluetooth connect arduino 8023
         run  sudo chmod a+rw /dev/arduino from "."
socat by Gerhard Rieger - see www.dest-unreach.org
socat version 1.7.1.3 on Jul 18 2013 09:16:59
   running on Linux version #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013, release 3.11.0-12-generic, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
         run  socat -d -d FILE:/dev/arduino,nonblock,raw,b57600,echo=0 TCP-LISTEN:8023,fork from "."
2014/05/21 00:28:19 socat[9044] N opening character device "/dev/arduino" for reading and writing
2014/05/21 00:28:19 socat[9044] N listening on AF=2 0.0.0.0:8023
```

And the program seem to be connect as the led on the bluetooth chip stop blinking.

I then run my program with the connection set as such :
`
connection :firmata, :adaptor => :firmata, :port => '127.0.0.1:8023'
`

I get this log message on the socat log : 

```
2014/05/21 00:30:28 socat[9044] N accepting connection from AF=2 127.0.0.1:46564 on AF=2 127.0.0.1:8023
2014/05/21 00:30:28 socat[9044] N forked off child process 9074
2014/05/21 00:30:28 socat[9044] N listening on AF=2 0.0.0.0:8023
2014/05/21 00:30:28 socat[9074] N starting data transfer loop with FDs [3,3] and [5,5]
```

but the connection get stalled ( nothing happens ) on the artoo terminal : 

```
~/ruby $ ./blue.rb 
I, [2014-05-21T00:30:28.339670 #9060]  INFO -- : Registering connection 'firmata'...
I, [2014-05-21T00:30:28.357920 #9060]  INFO -- : Registering device 'board'...
I, [2014-05-21T00:30:28.357987 #9060]  INFO -- : Registering device 'led_green'...
Starting
I, [2014-05-21T00:30:28.358072 #9060]  INFO -- : Preparing work...
I, [2014-05-21T00:30:28.359321 #9060]  INFO -- : Initializing connection firmata...
I, [2014-05-21T00:30:28.417617 #9060]  INFO -- : Initializing device board...
I, [2014-05-21T00:30:28.445056 #9060]  INFO -- : Initializing device led_green...
I, [2014-05-21T00:30:28.506183 #9060]  INFO -- : Starting work...
I, [2014-05-21T00:30:28.526913 #9060]  INFO -- : Connecting to 'firmata' on port '127.0.0.1:8023'...
```

Am i missing something ?

**Comment by solojavier** [comment]
Hi @eltados , I'm seeing the same behaviour in my local, seems to be an issue with socat... I'll research and come back to you when I found something... if you find anything further please let us know....

**Comment by eltados** [comment]
Cheers @solojavier , I will try to have a look at this before the end of the week and come back to you if my investigation are successful.

**Comment by solojavier** [comment]
Hi @eltados,

We've found a workaround to move forward. You could use the hybridgroup-serialport gem and don't use a socket to serial interface.

So you would need to:

`gem install hybridgroup-serialport`

and then change the example to something like this:

`connection :firmata, :adaptor => :firmata, :port => '/dev/rfcomm0'`

Let us know if that works for you... it worked for me using usb port....

**Comment by eltados** [comment]
Hi,
I have no problem connecting to the arduino using the usb cable but I cannot get the bluetooth connection to work either directly using the serial port or using socat.
I have tried to then tried to write a simple echo C program , load it to the and tried to communicate with it via bluetooth and that does not seem to be working neither. 
I'm not sure why , so, for the moment I'm going to rule out a problem with artoo until I can get this to work.

Cheers for your support, I will keep you posted if I manage to get anything working eventually.

**Comment by solojavier** [comment]
Hi,

Thanks for keeping us updated... It's ok to you if we close this issue?

You can come back if you find there is an issue with artoo.

I'll try to connect to arduino using bluetooth when I got a chance.
