### ISSUE TITLE
artoo won't start after installing artoo-arduino

### ISSUE THREAD

**Issue by chasseurmic** [hybridgroup/artoo-arduino#29]
After running `gem install artoo-arduino`, when I try to run artoo I keep getting the following error

```
/Users/michelangelo/.rvm/gems/ruby-2.0.0-p353/.artoo/commands/arduino.rb:3:in `<module:Commands>': uninitialized constant Artoo::Commands::Firmata (NameError)
    from /Users/michelangelo/.rvm/gems/ruby-2.0.0-p353/.artoo/commands/arduino.rb:2:in `<module:Artoo>'
    from /Users/michelangelo/.rvm/gems/ruby-2.0.0-p353/.artoo/commands/arduino.rb:1:in `<top (required)>'
```

Problem is independent from the version of Ruby I'm using. The same happens even with the latest (2.1.1) version. Any ideas of what the problem could be?

**Comment by chasseurmic** [comment]
Same goes with Rubinius:

`Missing or uninitialized constant: Artoo::Commands::Firmata (NameError)`

**Comment by chasseurmic** [comment]
Ok, so I see there was an update in version 1.4.2 where someone added a missing require in comands/arduino.rb `require 'artoo/commands/firmata'`

Problem is that the issue is not yet solved when installing and downloading the gem.

**Comment by solojavier** [comment]
We have just updated gem to version 1.4.3 correcting the change you mention, please re-open if you still find this error after updating artoo-arduino gem.
