### ISSUE TITLE
artoo install socat

### ISSUE THREAD

**Issue by bgilreath** [hybridgroup/artoo-arduino#32]
gems/artoo-1.6.7/lib/artoo/commands/install.rb:16:in `socat': uninitialized constant Artoo::Commands::Install::Bundler (NameError)

**Comment by bgilreath** [comment]
I just ran "brew install socat" from command prompt, and now it connects via socat

**Comment by solojavier** [comment]
@bgilreath could you provide more information about environment, OS, ruby version, etc?
