### ISSUE TITLE
Arduino access through wifi

### ISSUE THREAD

**Issue by chrizbo** [hybridgroup/artoo-arduino#35]
Interested in creating a project that would get sensor data coming in and have an actuator (similar to an LED activation). This would eventually be integrated into an ARDrone flying around, but just trying to get one piece working at a time. 

I have the Uno (with wifi shield), Yun and Wifi Redback to try with.

**Comment by solojavier** [comment]
Hi @chrizbo , I'm not sure how the wifi shield works in the arduino, not sure if that would be able tu use artoo and firmata protocol to communicate.

But you could totally control a drone or arduino remotely using for example a raspi or bbb running artoo and using our api to trigger the commands.

Could you provide more details of what are you trying to achieve?

**Comment by solojavier** [comment]
Also please check our new arduino-yun support blog for cylon, it might help you too: http://cylonjs.com/blog/2014/07/29/cylon-js-fun-with-the-arduino-yun/

**Comment by chrizbo** [comment]
It is not looking good for out-of-the-box use of an Arduino wifi shield with Artoo based on what I have seen online. There seem to be TCP/UDP methods. I'm going through some tutorials to see how to do it without Artoo.

I have been experimenting with the ARDrone with some success, but [have some problems when trying to integrate into classes](https://github.com/hybridgroup/artoo/issues/129). There seems to be some incorrect documentation I am going to write an issue for soon (e.g. it says things like `up` doesn't require a parameter but it does in thrust from what I can tell).

Raspberry Pi does seem like an option (just ordered the B+ today to try) by connecting sensors and actuators to the GPIO, but it will probably put me over the weight restrictions of about 100 g for the AR Drone 2.0. Even with a better battery people say it gets pretty sluggish with too much weight.

I'll check out the Cylon article to see if that helps at all too. 

Thanks and any other suggestions are appreciated.

**Comment by solojavier** [comment]
Let us know if we can help you further.

**Comment by chrizbo** [comment]
As a note, I am going to use a [Wifi Redback](http://www.arduino-hacks.com/arduino-wifi-redback-yellowjacket-compatible/), program a simplistic JSON server and use HTTParty to interface with it. 

Definitely not my ideal, but seems to work for my case. It would have been nice to use something like Firmata (change the hardware == change in Ruby) vs. this solution (change in hardware == change in Redback Arduino sketch and change in Ruby).

**Comment by solojavier** [comment]
Hi, 

Thanks for the note, let us know how that goes and if there is any feedback or specific feature you think we should have, please let us know. It's always useful for us...
