### ISSUE TITLE
Out of date documentation?

### ISSUE THREAD

**Issue by fearoffish** [hybridgroup/artoo-arduino#36]
In the README it mentions that we use:

```
artoo connect scan -t serial
```

However that fails to work on my Mac, with the latest gems for artoo and artoo-arduino.  However, installing gort worked beautifully.

**Comment by nickmjones** [comment]
+1, except gort doesn't seem to work very well for me.

**Comment by solojavier** [comment]
@littlerobothead What problem are you having?

**Comment by solojavier** [comment]
Readme has been updated: https://github.com/hybridgroup/artoo-arduino/commit/f34bf881c24cc7c865be25ea772697b6b8a55042

**Comment by nickmjones** [comment]
@solojavier Actually, in looking at it I was able to get it working. Initially, I was having trouble scanning but I think it was not to do with gort or artoo.

**Comment by solojavier** [comment]
Cool.. thanks!
